import { library } from '@fortawesome/fontawesome-svg-core';
import { faJs, 
  faPython,
  faJava,
  faCss3,
  faHtml5,
  faNodeJs,
  faVuejs,
  faPhp,
  faMicrosoft,
  faGithub,
  faAngular,
  faOpenai,
  faGitAlt,
  faLinkedin
} from '@fortawesome/free-brands-svg-icons';
import {
  faUserSecret,
  faThumbsUp,
  faBars,
  faUser,
  faInfo,
  faFolder,
  faHouse,
  faGraduationCap,
  faLaptopCode,
  faChevronDown,
  faXmark,
  faArrowRight,
  faMessage,
  faFileArrowDown,
  faSun,
  faMoon,
  faLightbulb,
  faCode,
  faDatabase,
  faCalendar,
  faChartLine,
  faDiagramProject,
  faServer,
  faRobot,
  faChartPie,
  faWindowRestore,
  faEnvelope,
  faPhone
} from '@fortawesome/free-solid-svg-icons';


// Función para inicializar y añadir los iconos a la librería
export function initializeFontAwesome() {
  library.add(
    faUserSecret,
    faThumbsUp,
    faBars,
    faUser,
    faInfo,
    faFolder,
    faHouse,
    faGraduationCap,
    faChartLine,
    faLaptopCode,
    faChevronDown,
    faXmark,
    faArrowRight,
    faMessage,
    faFileArrowDown,
    faSun,
    faMoon,
    faLightbulb,
    faCode,
    faCalendar,
    faEnvelope,
    faPhone,
    // Iconos de marcas
    faJs,
    faPython,
    faJava,
    faCss3,
    faHtml5,
    faNodeJs,
    faVuejs,
    faPhp,
    faMicrosoft,
    faGithub,
    faAngular,
    faDatabase,
    faOpenai,
    faDiagramProject,
    faServer,
    faRobot,
    faChartPie,
    faGitAlt,
    faWindowRestore,
    faEnvelope,
    faPhone,
    faLinkedin
  );
}